#!/usr/bin/env python3
"""Generates crates/cordial-runtime/src/guest_jni_table.rs from jni.h.

The guest's JNIEnv and JavaVM function tables are guest stubs, one per entry
(docs/vr/dynarmic-design.md §3.3), and each stub needs the entry's C
signature to move its arguments from AAPCS64 registers into a SysV call. That
is 229 + 5 signatures, and writing them by hand is exactly where a wrong one
goes unnoticed, so they are read from the jni.h libjnivm itself is compiled
against. The script refuses any type it cannot classify rather than guessing.

    tools/vr/gen-guest-jni.py > crates/cordial-runtime/src/guest_jni_table.rs
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HEADER = ROOT / "third_party/libjnivm/include/jni.h"

SCALARS = {
    "jint": "I32", "jsize": "I32", "jlong": "I64", "jboolean": "U8", "jbyte": "I8",
    "jchar": "U16", "jshort": "I16", "jfloat": "F32", "jdouble": "F64",
    "jobjectRefType": "I32",
}
HANDLES = {
    "jobject", "jclass", "jstring", "jthrowable", "jarray", "jobjectArray", "jbooleanArray",
    "jbyteArray", "jcharArray", "jshortArray", "jintArray", "jlongArray", "jfloatArray",
    "jdoubleArray", "jweak", "jmethodID", "jfieldID",
}


def classify(t):
    t = t.strip().replace("const ", "").strip()
    if t.endswith("*"):
        return "Ptr"
    if t in SCALARS:
        return SCALARS[t]
    if t in HANDLES:
        return "Ptr"
    if t == "void":
        return None
    sys.exit(f"gen-guest-jni: cannot classify C type {t!r}")


def ret(t):
    c = classify(t)
    if c is None:
        return "Ret::Void"
    if c == "F32":
        return "Ret::F32"
    if c == "F64":
        return "Ret::F64"
    return f"Ret::Int({c})"


def table(struct):
    text = HEADER.read_text()
    m = re.search(r"struct %s \{(.*?)\n\};" % struct, text, re.S)
    body = re.sub(r"/\*.*?\*/", "", m.group(1), flags=re.S)
    body = " ".join(body.split())
    out = []
    for decl in body.split(";"):
        decl = decl.strip()
        if not decl:
            continue
        if decl.startswith("void* reserved"):
            continue
        fm = re.fullmatch(r"(.+?)\s*\(\*(\w+)\)\((.*)\)", decl)
        if not fm:
            sys.exit(f"gen-guest-jni: cannot parse {decl!r}")
        rtype, name, args = fm.groups()
        args = [a.strip() for a in args.split(",")]
        form = "Form::Plain"
        if args[-1] == "...":
            form = "Form::Dots"
            args = args[:-1]
        elif args[-1] == "va_list":
            form = "Form::VaList"
            args = args[:-1]
        tys = [classify(a) for a in args]
        if any(t is None for t in tys):
            sys.exit(f"gen-guest-jni: void argument in {name}")
        out.append((name, tys, ret(rtype), form))
    return out


def emit(name, rows):
    print(f"pub(crate) const {name}: [Entry; {len(rows)}] = [")
    for n, tys, r, form in rows:
        print(f'    ("{n}", &[{", ".join(tys)}], {r}, {form}),')
    print("];")
    print()


env = table("JNINativeInterface")
vm = table("JNIInvokeInterface")
print("// Generated by tools/vr/gen-guest-jni.py from third_party/libjnivm/include/jni.h.")
print("// Do not edit; rerun the script.")
print()
print("use cordial_guest::{Ret, Ty::*};")
print()
print("use super::{Entry, Form};")
print()
print(f"/// `JNINativeInterface` after its four reserved words, in table order.")
emit("JNI_ENV", env)
print(f"/// `JNIInvokeInterface` after its three reserved words, in table order.")
emit("JNI_VM", vm)
