//! The arm64 guest's JNI boundary (docs/vr/dynarmic-design.md §3.3).
//!
//! libjnivm's `JavaVM` and `JNIEnv` are host objects whose function tables
//! hold x86-64 code, and the engine's `JNI_OnLoad` would jump into them as
//! arm64. So the guest gets its own `JavaVM` and `JNIEnv`, whose 5 and 229
//! table entries are guest stubs, each moving its call into libjnivm's entry
//! of the same index. The signatures come from the jni.h libjnivm is built
//! against (`guest_jni_table.rs`, generated by `tools/vr/gen-guest-jni.py`).
//!
//! Four things are more than a register move:
//!
//! * **The `JNIEnv*` argument.** The guest passes its own; libjnivm is given
//!   the calling thread's host env instead.
//! * **The variadic `Call*Method`/`NewObject` families.** `...` and `va_list`
//!   say nothing about their arguments; the method's descriptor does. They
//!   are read by descriptor (with C's promotions: a `float` arrives as a
//!   `double`, anything narrower than `int` as an `int`), packed into a
//!   `jvalue` array, and passed to the host's `A` form.
//! * **`RegisterNatives`.** Each `fnPtr` is guest code libjnivm will later
//!   call as its own, so it is registered as a host entry point
//!   (`cordial_guest::host_entry`) built from the method's descriptor, whose
//!   first argument is turned back into the guest's `JNIEnv*` on the way in.
//! * **`GetJavaVM`, `GetEnv`, `AttachCurrentThread`.** They hand out the
//!   guest's objects, never the host's.
//!
//! **A `JNIEnv` per thread**, as on Android, each with its own copy of the
//! function table. One shared env was enough for M3's single thread and
//! wrong the moment a second attached: the engine interposes on the env it is
//! given -- it saves `env->functions` and installs its own table -- so on a
//! shared env the second thread's interposition saved the first one's
//! wrapper as "the original", and every call through it then called itself
//! until the guest stack ran out (§9.3).

use std::ffi::{c_char, c_void, CStr};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, OnceLock};

use cordial_guest::{Call, Fault, Handler, Ret, Runtime, Ty, VaList};

#[path = "guest_jni_table.rs"]
mod table;

/// How a table entry takes its arguments beyond the named ones.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Form {
    Plain,
    Dots,
    VaList,
}

pub(crate) type Entry = (&'static str, &'static [Ty], Ret, Form);

extern "C" {
    fn cordial_jni_thread_env() -> *mut c_void;
    fn cordial_jni_method_signature(method: *mut c_void) -> *const c_char;
    fn cordial_jni_method_name(method: *mut c_void) -> *const c_char;
}

const JNI_OK: i32 = 0;

/// The guest's objects: `JNIEnv` and `JavaVM` are each one word pointing at
/// a table of stub addresses, laid out as jni.h lays out the host's. Boxed
/// and never freed, since the guest keeps the pointers for the process's
/// life.
struct GuestJni {
    env_table: Box<[u64; 4 + 229]>,
    vm: Box<[u64; 1]>,
    _vm_table: Box<[u64; 3 + 5]>,
    host_vm: u64,
}

static GUEST: OnceLock<GuestJni> = OnceLock::new();
static NATIVES: AtomicUsize = AtomicUsize::new(0);

thread_local! {
    /// This thread's guest `JNIEnv*`, made on first use.
    static THREAD_ENV: std::cell::Cell<u64> = const { std::cell::Cell::new(0) };
}

/// Every guest `JNIEnv*` handed out, on any thread.
static ENVS: std::sync::Mutex<Vec<u64>> = std::sync::Mutex::new(Vec::new());

/// The calling thread's guest `JNIEnv*`: one word pointing at the thread's
/// own copy of the stub table. Never freed, since the engine may keep the
/// pointer after the thread is gone.
fn guest_env_ptr() -> u64 {
    let Some(g) = GUEST.get() else { return 0 };
    THREAD_ENV.with(|e| {
        if e.get() == 0 {
            let table: &'static mut [u64; 4 + 229] = Box::leak(g.env_table.clone());
            let env: &'static mut [u64; 1] = Box::leak(Box::new([table as *mut [u64; 233] as u64]));
            let p = env as *mut [u64; 1] as u64;
            ENVS.lock().unwrap().push(p);
            e.set(p);
        }
        e.get()
    })
}

fn guest_vm_ptr() -> u64 {
    GUEST.get().map_or(0, |g| &*g.vm as *const [u64; 1] as u64)
}

/// How many guest natives have been registered with libjnivm.
pub fn registered_natives() -> usize {
    NATIVES.load(Ordering::Relaxed)
}

fn host_env(name: &str) -> Result<u64, Fault> {
    // SAFETY: returns null when there is no VM, which is checked.
    let e = unsafe { cordial_jni_thread_env() } as u64;
    if e == 0 {
        return Err(Fault::Unsupported { thunk: name.into(), why: "no host JNIEnv for this thread".into() });
    }
    Ok(e)
}

/// The host env's function-table entry `index` (after the four reserved
/// words).
fn host_fn(env: u64, index: usize) -> *const c_void {
    // SAFETY: a JNIEnv is a pointer to its function table.
    unsafe { *((*(env as *const *const u64)).add(4 + index)) as *const c_void }
}

/// The argument types a JNI method descriptor names, and its return.
fn descriptor(sig: &[u8]) -> Option<(Vec<u8>, u8)> {
    let mut i = 1;
    if sig.first() != Some(&b'(') {
        return None;
    }
    let mut args = Vec::new();
    while *sig.get(i)? != b')' {
        let start = sig[i];
        while sig[i] == b'[' {
            i += 1;
        }
        if sig[i] == b'L' {
            while *sig.get(i)? != b';' {
                i += 1;
            }
        }
        i += 1;
        args.push(if start == b'[' { b'L' } else { start });
    }
    let r = *sig.get(i + 1)?;
    Some((args, if r == b'[' { b'L' } else { r }))
}

/// How a descriptor letter travels through `...` or a `va_list` after C's
/// default promotions.
fn promoted(c: u8) -> Ty {
    match c {
        b'J' => Ty::I64,
        b'F' | b'D' => Ty::F64,
        b'L' => Ty::Ptr,
        _ => Ty::I32,
    }
}

/// A raw promoted argument as the `jvalue` member its letter names.
fn jvalue(c: u8, raw: u64) -> u64 {
    match c {
        b'Z' => raw & 0xff,
        b'B' => raw & 0xff,
        b'C' | b'S' => raw & 0xffff,
        b'I' => raw & 0xffff_ffff,
        b'F' => (f64::from_bits(raw) as f32).to_bits() as u64,
        _ => raw,
    }
}

/// A descriptor letter as a SysV/AAPCS64 argument or return type.
fn ty(c: u8) -> Ty {
    match c {
        b'Z' => Ty::U8,
        b'B' => Ty::I8,
        b'C' => Ty::U16,
        b'S' => Ty::I16,
        b'I' => Ty::I32,
        b'J' => Ty::I64,
        b'F' => Ty::F32,
        b'D' => Ty::F64,
        _ => Ty::Ptr,
    }
}

fn ret(c: u8) -> Ret {
    match c {
        b'V' => Ret::Void,
        b'F' => Ret::F32,
        b'D' => Ret::F64,
        c => Ret::Int(ty(c)),
    }
}

/// One `JNIEnv` entry that is a plain register move, with the env swapped.
fn plain(index: usize, e: &'static Entry) -> Handler {
    let (name, args, r, _) = *e;
    Box::new(move |c| {
        let env = host_env(name)?;
        let mut vals = cordial_guest::collect(c, args);
        vals[0] = env;
        // SAFETY: the host function named by `name`, called with the types its
        // C declaration gives; pointers are the guest's, which are host addresses.
        let out = unsafe { cordial_guest::invoke(name, host_fn(env, index), args, &vals) }?;
        cordial_guest::write_ret(c, r, &out);
        Ok(())
    })
}

/// A `...` or `va_list` entry, moved onto its `A` form: the named arguments
/// as they are, then a `jvalue` array read by the method's descriptor.
fn variadic(index: usize, e: &'static Entry) -> Handler {
    let (name, args, r, form) = *e;
    // The `A` form is the next entry after `V`, two after `...`.
    let a_index = index + if form == Form::Dots { 2 } else { 1 };
    let named = args.len();
    Box::new(move |c| {
        let env = host_env(name)?;
        let method = c.x(named as u32 - 1);
        // SAFETY: a jmethodID libjnivm issued, or null.
        let sig = unsafe { cordial_jni_method_signature(method as *mut c_void) };
        if sig.is_null() {
            return Err(Fault::Unsupported { thunk: name.into(), why: "null jmethodID".into() });
        }
        // SAFETY: a C string owned by the Method.
        let sig = unsafe { CStr::from_ptr(sig) }.to_bytes();
        let Some((letters, _)) = descriptor(sig) else {
            return Err(Fault::Unsupported {
                thunk: name.into(),
                why: format!("unparseable descriptor {}", String::from_utf8_lossy(sig)),
            });
        };
        // Which Java method the engine reached, when a button does nothing and
        // nothing else is logged: a call that jnivm answers with a default goes
        // by without a trace otherwise.
        if std::env::var_os("CORDIAL_GUEST_JNI_LOG").is_some() {
            // SAFETY: as for `sig` above.
            let mname = unsafe { CStr::from_ptr(cordial_jni_method_name(method as *mut c_void)) };
            eprintln!("[guest-jni] {name} {}{}", mname.to_string_lossy(), String::from_utf8_lossy(sig));
        }
        let promoted_tys: Vec<Ty> = letters.iter().map(|&l| promoted(l)).collect();
        let raws: Vec<u64> = if form == Form::Dots {
            let all: Vec<Ty> = args.iter().copied().chain(promoted_tys.iter().copied()).collect();
            cordial_guest::collect(c, &all)[named..].to_vec()
        } else {
            // SAFETY: by AAPCS64 a va_list argument points at the caller's.
            let mut va = unsafe { VaList::read(c.x(named as u32)) };
            promoted_tys.iter().map(|&t| va.next(t)).collect()
        };
        let jvalues: Vec<u64> = letters.iter().zip(&raws).map(|(&l, &v)| jvalue(l, v)).collect();
        let mut vals = cordial_guest::collect(c, args);
        vals[0] = env;
        vals.push(jvalues.as_ptr() as u64);
        let a_args: Vec<Ty> = args.iter().copied().chain([Ty::Ptr]).collect();
        // SAFETY: the host function named by `name`, called with the types its
        // C declaration gives; pointers are the guest's, which are host addresses.
        let out = unsafe { cordial_guest::invoke(name, host_fn(env, a_index), &a_args, &vals) }?;
        cordial_guest::write_ret(c, r, &out);
        Ok(())
    })
}

/// A host entry for the guest JNI native at `pc`, whose descriptor's
/// argument letters and return letter are `letters` and `r`: libjnivm or
/// Cordial calls it as a SysV function taking `(JNIEnv*, jobject or jclass,
/// ...)`, and the guest receives its own `JNIEnv*` in place of the host's.
fn native_entry(rt: &Arc<Runtime>, label: &str, pc: u64, letters: &[u8], r: u8) -> Result<*const c_void, String> {
    let args: Vec<Ty> = [Ty::Ptr, Ty::Ptr].into_iter().chain(letters.iter().map(|&l| ty(l))).collect();
    let map: cordial_guest::ArgMap = Box::new(|i, v| if i == 0 { guest_env_ptr() } else { v });
    cordial_guest::host_entry(rt, label, pc, args, ret(r), Some(map))
}

/// Makes `lib`'s `Java_*` exports and `JNI_OnLoad` callable by host code,
/// through `linker::set_symbol_filter`: `cordial-run`'s bring-up, and the web
/// view, linking and permission bridges, each resolve an engine native by
/// name and call it as their own.
///
/// Each export becomes a host entry built from the descriptor its `native`
/// method is declared with in the APK's dex (`guest_dex`), made once and
/// reused. `JNI_OnLoad` receives the guest `JavaVM` in place of the host's.
/// Any other name of the guest library, or an export whose descriptor the
/// dex does not give, is refused with a line saying so: a guest address
/// handed to a host caller would be run as x86.
pub fn install_symbol_filter(rt: &Arc<Runtime>, lib: cordial_linker_sys::Library, apk: &std::path::Path)
    -> Result<usize, String>
{
    use std::collections::HashMap;
    use std::sync::Mutex;

    let descriptors = crate::guest_dex::native_descriptors(apk)?;
    let n = descriptors.len();
    let made: Mutex<HashMap<String, usize>> = Mutex::new(HashMap::new());
    let rt = rt.clone();
    let lib = lib.as_ptr() as usize;
    let filter = move |l: cordial_linker_sys::Library, name: &str, p: *mut c_void| -> Option<*mut c_void> {
        if l.as_ptr() as usize != lib {
            return Some(p);
        }
        let mut made = made.lock().unwrap();
        if let Some(&e) = made.get(name) {
            return Some(e as *mut c_void);
        }
        let entry = if name == "JNI_OnLoad" {
            let rt2 = rt.clone();
            let map: cordial_guest::ArgMap = Box::new(move |i, v| {
                if i == 0 {
                    guest_vm(&rt2, v).unwrap_or(0)
                } else {
                    v
                }
            });
            cordial_guest::host_entry(&rt, name, p as u64, vec![Ty::Ptr, Ty::Ptr], Ret::Int(Ty::I32), Some(map))
        } else if let Some(sig) = descriptors.get(name) {
            match descriptor(sig.as_bytes()) {
                Some((letters, r)) => native_entry(&rt, name, p as u64, &letters, r),
                None => Err(format!("unparseable descriptor {sig}")),
            }
        } else {
            Err("no native with this name is declared in the APK's dex".into())
        };
        match entry {
            Ok(e) => {
                made.insert(name.to_owned(), e as usize);
                Some(e as *mut c_void)
            }
            Err(why) => {
                eprintln!("guest: {name} is not callable from the host: {why}");
                None
            }
        }
    };
    if !cordial_linker_sys::set_symbol_filter(Box::new(filter)) {
        return Err("a symbol filter is already installed".into());
    }
    Ok(n)
}

/// `{ const char* name; const char* signature; void* fnPtr; }`, the same on
/// both sides.
#[repr(C)]
struct NativeMethod {
    name: *const c_char,
    signature: *const c_char,
    fn_ptr: *const c_void,
}

/// `RegisterNatives(env, clazz, methods, n)`, each guest `fnPtr` behind a
/// host entry point built from its descriptor.
fn register_natives(index: usize, rt: Arc<Runtime>) -> Handler {
    Box::new(move |c| {
        let name = "RegisterNatives";
        let env = host_env(name)?;
        let (clazz, methods, n) = (c.x(1), c.x(2) as *const NativeMethod, c.x(3) as u32 as i32);
        let mut host = Vec::with_capacity(n.max(0) as usize);
        for i in 0..n.max(0) as usize {
            // SAFETY: the guest's array of n entries.
            let m = unsafe { &*methods.add(i) };
            // SAFETY: C strings from the guest.
            let (mname, msig) = unsafe { (CStr::from_ptr(m.name), CStr::from_ptr(m.signature)) };
            let Some((letters, r)) = descriptor(msig.to_bytes()) else {
                return Err(Fault::Unsupported {
                    thunk: name.into(),
                    why: format!("unparseable descriptor {msig:?} for {mname:?}"),
                });
            };
            let label = format!("{}{}", mname.to_string_lossy(), msig.to_string_lossy());
            let entry = native_entry(&rt, &label, m.fn_ptr as u64, &letters, r)
                .map_err(|why| Fault::Unsupported { thunk: name.into(), why })?;
            host.push(NativeMethod { name: m.name, signature: m.signature, fn_ptr: entry });
        }
        // SAFETY: the host function named by `name`, called with the types its
        // C declaration gives; pointers are the guest's, which are host addresses.
        let out = unsafe { cordial_guest::invoke(name, host_fn(env, index), &[Ty::Ptr, Ty::Ptr, Ty::Ptr, Ty::I32],
                                        &[env, clazz, host.as_ptr() as u64, n as u32 as u64]) }?;
        if out.rax as u32 as i32 == JNI_OK {
            NATIVES.fetch_add(host.len(), Ordering::Relaxed);
        }
        c.set_x(0, out.rax as u32 as u64);
        Ok(())
    })
}

fn get_java_vm() -> Handler {
    Box::new(|c| {
        // SAFETY: the guest's JavaVM** out-parameter.
        unsafe { (c.x(1) as *mut u64).write(guest_vm_ptr()) };
        c.set_x(0, JNI_OK as u64);
        Ok(())
    })
}

/// The host `JavaVM`'s entry `index` (after its three reserved words).
fn host_vm_fn(vm: u64, index: usize) -> *const c_void {
    // SAFETY: a JavaVM is a pointer to its function table.
    unsafe { *((*(vm as *const *const u64)).add(3 + index)) as *const c_void }
}

/// A `JavaVM` entry. The ones that hand out a `JNIEnv*` hand out the
/// guest's, after the host call has succeeded; the rest pass through.
fn vm_entry(index: usize, e: &'static Entry, host_vm: u64) -> Handler {
    let (name, args, r, _) = *e;
    Box::new(move |c: &Call| {
        let hands_out_env = matches!(name, "AttachCurrentThread" | "AttachCurrentThreadAsDaemon" | "GetEnv");
        let mut vals = cordial_guest::collect(c, args);
        vals[0] = host_vm;
        let mut slot = 0u64;
        if hands_out_env {
            vals[1] = &mut slot as *mut u64 as u64;
        }
        // SAFETY: the host function named by `name`, called with the types its
        // C declaration gives; pointers are the guest's, which are host addresses.
        let out = unsafe { cordial_guest::invoke(name, host_vm_fn(host_vm, index), args, &vals) }?;
        if hands_out_env && out.rax as u32 as i32 == JNI_OK && c.x(1) != 0 {
            // SAFETY: the guest's JNIEnv**/void** out-parameter.
            unsafe { (c.x(1) as *mut u64).write(if slot == 0 { 0 } else { guest_env_ptr() }) };
        }
        cordial_guest::write_ret(c, r, &out);
        Ok(())
    })
}

/// Builds the guest's `JavaVM` and `JNIEnv` over the host `JavaVM` at
/// `host_vm`, and returns the guest `JavaVM*` to pass to `JNI_OnLoad`.
pub fn guest_vm(rt: &Arc<Runtime>, host_vm: u64) -> Result<u64, String> {
    if host_vm == 0 {
        return Err("no host JavaVM".into());
    }
    if GUEST.get().is_some() {
        return Ok(guest_vm_ptr());
    }
    let mut env_table = Box::new([0u64; 4 + 229]);
    for (i, e) in table::JNI_ENV.iter().enumerate() {
        let h = match (e.0, e.3) {
            ("RegisterNatives", _) => register_natives(i, rt.clone()),
            ("GetJavaVM", _) => get_java_vm(),
            (_, Form::Plain) => plain(i, e),
            _ => variadic(i, e),
        };
        env_table[4 + i] = rt.register(&format!("JNIEnv::{}", e.0), h);
    }
    let mut vm_table = Box::new([0u64; 3 + 5]);
    for (i, e) in table::JNI_VM.iter().enumerate() {
        vm_table[3 + i] = rt.register(&format!("JavaVM::{}", e.0), vm_entry(i, e, host_vm));
    }
    let vm = Box::new([&*vm_table as *const [u64; 8] as u64]);
    let _ = GUEST.set(GuestJni { env_table, vm, _vm_table: vm_table, host_vm });
    Ok(guest_vm_ptr())
}

/// The host `JavaVM` the guest's is built over.
pub fn host_vm() -> Option<u64> {
    GUEST.get().map(|g| g.host_vm)
}

/// Maps a guest `JNIEnv*` to the calling thread's host one, for imports
/// that take an env (`AAssetManager_fromJava`), or passes it through if it
/// is not the guest's.
pub fn host_env_for(guest_env: u64) -> Option<u64> {
    if guest_env != 0 && ENVS.lock().unwrap().contains(&guest_env) {
        // SAFETY: returns null when there is no VM.
        let e = unsafe { cordial_jni_thread_env() } as u64;
        (e != 0).then_some(e)
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_tables_have_jni_h_sizes() {
        assert_eq!(table::JNI_ENV.len(), 229);
        assert_eq!(table::JNI_VM.len(), 5);
        assert_eq!(table::JNI_ENV[0].0, "GetVersion");
        assert_eq!(table::JNI_ENV[228].0, "GetObjectRefType");
    }

    /// Every `...` entry is followed by its `V` and `A` forms, which is what
    /// the index arithmetic in `variadic` relies on.
    #[test]
    fn every_variadic_entry_has_its_a_form_where_expected() {
        for (i, e) in table::JNI_ENV.iter().enumerate() {
            if e.3 == Form::Dots {
                assert_eq!(table::JNI_ENV[i + 1].0, format!("{}V", e.0));
                assert_eq!(table::JNI_ENV[i + 2].0, format!("{}A", e.0));
                assert_eq!(table::JNI_ENV[i + 1].3, Form::VaList);
            }
        }
    }

    #[test]
    fn descriptors_parse_with_arrays_and_objects() {
        let (a, r) = descriptor(b"(I[JLjava/lang/String;[[Lfoo;FZ)D").unwrap();
        assert_eq!(a, b"ILLLFZ");
        assert_eq!(r, b'D');
        let (a, r) = descriptor(b"()[B").unwrap();
        assert!(a.is_empty());
        assert_eq!(r, b'L');
    }

    #[test]
    fn promoted_float_becomes_a_jvalue_float() {
        assert_eq!(jvalue(b'F', 1.5f64.to_bits()), 1.5f32.to_bits() as u64);
        assert_eq!(jvalue(b'Z', 0xffff_ff01), 1);
    }
}
